# Generated by Django 4.1.3 on 2022-11-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contact', models.IntegerField(unique=True)),
                ('contact_ext', models.IntegerField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('image_md', models.ImageField(upload_to='images')),
                ('image_lg', models.ImageField(upload_to='images')),
                ('image_thumbnail', models.ImageField(upload_to='images')),
                ('team', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('last_login', models.DateField(auto_now=True)),
                ('logged_in', models.BooleanField(default=False)),
            ],
        ),
    ]
